### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by owen-adams2021** [owen-adams2021/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create index.html, styles.css, main.js, data.js files
- [x] Create an HTML Skeleton
- [x] Link your styles.css, main.js, and data.js files to your index.html
- [x] Create a div element for the car container
- [x] Style the div to take up the entire width of the browser
- [x] Set the background color to your liking
- [x] Add image of F1 Car to images folder
- [x] Implement an image of a car
- [x] Style the size of the car
