### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by owen-adams2021** [owen-adams2021/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Query the Dom for the car image
- [x] Create function to rotate the image of the car
- [x] Add eventListener to the window for key clicks
- [x] If arrow left arrow is clicked, car turns West
- [x] Changes styling to add rotate property West
- [x] If arrow up arrow is clicked, car turns North
- [x] Changes styling to add rotate property North
- [x] If arrow right arrow is clicked, car turns East
- [x] Changes styling to add rotate property East
- [x] If arrow down arrow is clicked, car turns South
- [x] Changes styling to add rotate property South
- [x] Once arrow keys are functioning properly, add features to WASD
