### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by owen-adams2021** [owen-adams2021/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Add absolute positioning to the image
- [x] Add eventListener to spacebar
- [x] Create a new function to change offset of the car
- [x] Create setInterval to run function every 16 miliseconds
- [x] In eventListener, if spacebar pressed setInterval will run function to change the offset of the car.
- [x] If spacebar is pressed down, car will move 3 pixels every 16 miliseconds
